language: node_js
node_js:
  - "10"

cache:
  directories:
    - "node_modules"

branches:
  only:
  - release
  - develop

install:
  - yarn install
  - yarn build
  - cd functions
  - yarn install
  - cd ..

script:
  - echo "Skipping tests"

deploy:
  - provider: firebase
    skip-cleanup: true
    project: "lab-website-72041"
    token: $FIREBASE_CI
    on:
      branch: release
  - provider: firebase
    skip-cleanup: true
    project: "lab-website-develop-f0781"
    token: $FIREBASE_CI
    on:
      branch: develop


# GitHub Pages
#  provider: pages
#  skip-cleanup: true
#  github-token: $GITHUB_ACCESS_TOKEN
#  target-branch: gh-pages
#  local-dir: dist
#  on:
#    branch: release
