language: node_js
node_js:
  - "10"

cache:
  directories:
    - "node_modules"

branches:
  only:
  - release

install:
  - yarn install
  - yarn build

script:
  - echo "Skipping tests"

deploy:
  - provider: firebase
    skip-cleanup: true
    project: "lab-website-72041"
    token:
      secure: $FIREBASE_CI
    on:
      branch: release

# GitHub Pages
#  provider: pages
#  skip-cleanup: true
#  github-token: $GITHUB_ACCESS_TOKEN
#  target-branch: gh-pages
#  local-dir: dist
#  on:
#    branch: release
