language: node_js
node_js:
  - "10"

cache:
  directories:
    - "node_modules"

branches:
  only:
  - release
  - develop

install:
  - yarn install
  - yarn build
  - pwd
  - ls
  - cd functions
  - pws
  - ls
  - yarn install
  - cd ../
  - pwd
  - ls

script:
  - echo "Skipping tests"

deploy:
  # - provider: firebase
  #   skip-cleanup: true
  #   token: $FIREBASE_CI
  #   on:
  #     branch: release
  - provider: firebase
    # cleanup: true
    # project: "develop"
    token:
      secure: $FIREBASE_CI
    on:
      branch: develop


# GitHub Pages
#  provider: pages
#  skip-cleanup: true
#  github-token: $GITHUB_ACCESS_TOKEN
#  target-branch: gh-pages
#  local-dir: dist
#  on:
#    branch: release
